# Generated by Django 3.2.7 on 2021-10-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211015_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cover_image',
        ),
    ]
